#ifndef INC_PACKDATA_H_
#define INC_PACKDATA_H_

#define MAX_CELL_IMBALANCE_V    0.1f

#define MAX_TEMP_SENSOR_VALUE_C     120.0f
#define MIN_TEMP_SENSOR_VALUE_C     -40.0f

#define MAX_VOLTAGE_SENSOR_VALUE_V  5.0f
#define MIN_VOLTAGE_SENSOR_VALUE_V  0.0f



#endif /* INC_PACKDATA_H_ */
